### ISSUE TITLE
CUDA errror 'out of memory'

### ISSUE THREAD

**Issue by saltytacozz** [btcz/zhasher#6]
When running >4 GPUs CUDA throws the following error:
[16:00:37][0x00001af0] miner#3 | CUDA error 'out of memory' in func 'eq_cuda_context::eq_cuda_context' line 899

I have tested by using various GPUs from the 6 in my rig and each time I attempt to activate a 5th GPU the error is thrown.

zhasher.exe -cd 0 1 2 3 4 5 -cv 1 -l mine-btcz-na.equipool.1ds.us:49951 -u tmWjhEGegvBSR5c49JNkk4PDyzDFfiNkGBT - ERROR

zhasher.exe -cd 0 1 2 3 -cv 1 -l mine-btcz-na.equipool.1ds.us:49951 -u tmWjhEGegvBSR5c49JNkk4PDyzDFfiNkGBT - NO ERROR

**Comment by egyptianbman** [comment]
Additional info from our discord convo:

```
Me - Could it be a specific gpu that's triggering it?
Whichever one you added as #4

salty - No, mixed the GPUs
0 1 2 3 - Fine
2 3 4 5 - Fine
0 1 2 3 4 - Error
1 2 3 4 5 - Error
right now I'm hashing with 1 2 3 4
```

**Comment by saltytacozz** [comment]
This issue was resolved by increasing the paging file. I'm sure someone smarter than me knows why it is demanding a larger portion depending on number of GPUs
