### ISSUE TITLE
Unspecified launch failure 

### ISSUE THREAD

**Issue by saltytacozz** [btcz/zhasher#7]
During normal mining

[16:16:42][0x000017a4] miner#5 | CUDA error 'unspecified launch failure' in func 'eq_cuda_context::solve' line 966

Miner stops

**Comment by renuzit** [comment]
Are you overclock the GPUs? We've heard reports that zhasher is sensitive to overclocking.

**Comment by saltytacozz** [comment]
That was the issue, reset core clock OC to 0 and ran miner for 2 hours without issue.

Thanks!
